### PR TITLE
Small Spelling Fix On Readme

### PR DESCRIPTION
**Pull request by irishgordo**
Hey there!

Happy Tuesday!

This README and the New Relic docs / guides / community forms - are incredible!
Kudos to all the contributors that have made the ecosystem what it is!

Just happened to see a small area where I could push up a small spelling fix.

Super willing to iterate and improve this PR however needed!

### CODE REVIEW

**Review by mrickard — APPROVED** [review]
Thank you!

**Comment by mrickard** [comment]
@irishgordo Would you be able to amend your commit so that it's signed? that's a requirement for this repo. Thank you!

**Comment by irishgordo** [comment]
@mrickard signing it is a great idea!  :)
I've created a gpg key, linked it to my account, tied it into git, amended the commit and force pushed out on this branch - I do like seeing the "Verified" next to my name now heheh

**Review by mrickard — APPROVED** [review]
Thank you!

**Comment by irishgordo** [comment]
@mrickard ya welcome!
Glad I could make a small contribution to an awesome project!

**Pull request merged**
